on:
  push:
    paths:
      - 'recipes/**'


name: Recipe CI

jobs:
  validate_recipes:
    name: Validate Recipes
    needs: [clippy, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --all-features -- validate
